/**
 * Generated by scripts/generate-config.js — do not commit real secrets.
 * Local: copy .env.example → .env and run: npm run generate-config
 * Netlify: /js/config.js is served by netlify/functions/public-config.js from env vars.
 */
(function () {
    'use strict';
    window.SUPABASE_URL = window.SUPABASE_URL || "https://wftupkrpgwdewnytlgms.supabase.co";
    window.SUPABASE_ANON_KEY = window.SUPABASE_ANON_KEY || window.SUPABASE_PUBLISHABLE_KEY || "sb_publishable_WpRHh9_NVxCkTzYHOFggTw_Z2VwHsvd";
    window.SUPABASE_OWNER_EMAIL = window.SUPABASE_OWNER_EMAIL || "the_fantasy_maker@hotmail.com";
    window.TURNSTILE_SITE_KEY = window.TURNSTILE_SITE_KEY || "0x4AAAAAAD6Cy3pzCik3miQZ";
})();
