// Plant Image Search Terms
// These search terms can be used for fetching images from external APIs
// Note: Plant data has been migrated to data/plants/*.json files

const plantImageSources = {
    // Search terms optimized for image APIs
    defaultImageSearchTerms: {
        1: "Fittonia albivenis nerve plant",
        2: "Soleirolia soleirolii baby tears",
        3: "Pilea involucrata friendship plant",
        4: "Ficus pumila creeping fig",
        5: "Epipremnum aureum golden pothos",
        6: "Bromeliad vivarium plant",
        7: "Begonia vivarium species",
        8: "Peperomia small variety",
        9: "Microsorum pteropus Java fern aquarium",
        10: "Anubias barteri aquarium plant",
        11: "Echinodorus Amazon sword aquarium",
        12: "Cryptocoryne aquarium plant",
        13: "Taxiphyllum barbieri Java moss",
        14: "Eleocharis parvula dwarf hairgrass",
        15: "Aegagropila linnaei marimo moss ball",
        16: "Selaginella clubmoss terrarium",
        17: "Alocasia Amazonica dwarf",
        18: "Pellionia repens terrarium",
        19: "Hypoestes phyllostachya polka dot plant",
        20: "Oxalis triangularis purple shamrock",
        21: "Fittonia verschaffeltii mini",
        22: "Hoya carnosa",
        23: "Ceropegia woodii string of hearts",
        24: "Pellaea rotundifolia button fern",
        25: "Tradescantia zebrina",
        26: "Pilea microphylla artillery fern",
        27: "Saintpaulia ionantha mini African violet",
        28: "Syngonium podophyllum dwarf",
        29: "Rotala rotundifolia emersed",
        30: "Micranthemum Monte Carlo emersed",
        31: "Pilea cadierei aluminum plant",
        32: "Nephrolepis cordifolia Duffii lemon button fern",
        33: "Saxifraga stolonifera strawberry begonia",
        34: "Adiantum raddianum Fragrans mini maidenhair",
        35: "Dichondra argentea silver falls",
        36: "Rotala rotundifolia aquarium",
        37: "Hygrophila difformis water wisteria",
        38: "Ceratophyllum demersum hornwort",
        39: "Egeria densa anacharis",
        40: "Vallisneria aquarium plant",
        41: "Sagittaria subulata",
        42: "Ludwigia repens",
        43: "Bacopa caroliniana",
        44: "Sagittaria subulata dwarf",
        45: "Micranthemum Monte Carlo aquarium",
        46: "Pistia stratiotes dwarf water lettuce",
        47: "Phyllanthus fluitans red root floater",
        48: "Riccia fluitans crystalwort",
        49: "Limnobium laevigatum frogbit",
        50: "Ceratopteris thalictroides water sprite",
        51: "Hypnum sheet moss terrarium",
        52: "Leucobryum glaucum cushion moss",
        53: "Syntrichia ruralis star moss",
        54: "Leucobryum albidum pillow moss",
        55: "Dicranum scoparium mood moss",
        56: "Thuidium delicatulum fern moss",
        57: "Sphagnum moss terrarium",
        58: "Taxiphyllum Flame moss terrarium",
        59: "Vesicularia montagnei Christmas moss aquarium",
        60: "Vesicularia ferriei weeping moss aquarium",
        61: "Fissidens fontanus Phoenix moss aquarium",
        62: "Taxiphyllum Flame moss aquarium",
        63: "Chaetomorpha linum macroalgae",
        64: "Halimeda macroalgae",
        65: "Halymenia durvillei dragons tongue algae",
        66: "Gracilaria macroalgae",
        67: "Monosolenium tenerum mini pellia",
        68: "Riccardia chamedryfolia liverwort",
        69: "Lichens terrarium vivarium",
        70: "Lemna minor duckweed",
        71: "Salvinia minima floating fern",
        72: "Azolla filiculoides water fern",
        73: "Phalaenopsis miniature orchid",
        74: "Masdevallia orchid terrarium",
        75: "Pleurothallis orchid terrarium",
        76: "Lepanthes mini orchid",
        77: "Dracula orchid monkey face",
        78: "Bulbophyllum miniature orchid",
        79: "Ludisia discolor jewel orchid",
        80: "Anthurium andraeanum miniature",
        81: "Nepenthes pitcher plant mini",
        82: "Dionaea muscipula venus flytrap",
        83: "Tillandsia air plant miniature",
        84: "Heliamphora sun pitcher",
        85: "Utricularia bladderwort",
        86: "Drosera sundew miniature",
        87: "Myrmecodia ant plant",
        88: "Dischidia epiphytic succulent",
        89: "Medinilla magnifica dwarf",
        90: "Rhipsalis mini epiphytic cactus",
        91: "Nephrolepis exaltata Boston fern mini",
        92: "Davallia fejeensis rabbits foot fern",
        93: "Platycerium bifurcatum staghorn fern mini",
        94: "Asplenium nidus birds nest fern mini",
        95: "Microsorum diversifolium kangaroo paw fern",
        96: "Phlebodium aureum blue star fern",
        97: "Echeveria miniature succulent",
        98: "Haworthia succulent",
        99: "Senecio rowleyanus string of pearls",
        100: "Lithops living stones",
        101: "Aloe miniature",
        102: "Crassula miniature jade",
        103: "Sedum miniature stonecrop",
        104: "Sarracenia pitcher plant",
        105: "Pinguicula butterwort",
        106: "Cephalotus follicularis Albany pitcher",
        107: "Darlingtonia californica cobra lily",
        108: "Tillandsia usneoides Spanish moss",
        109: "Tillandsia ionantha air plant",
        110: "Tillandsia xerographica",
        111: "Tillandsia caput-medusae",
        112: "Tillandsia brachycaulos"
    },
    
    // Alternative: Direct image URLs from public plant databases (if available)
    // These would be populated with actual URLs from:
    // - iNaturalist API
    // - PlantNet API  
    // - Wikimedia Commons
    // - Open source plant databases
    directImageUrls: {
        // Example format (would need actual URLs):
        // 1: "https://example.com/fittonia.jpg"
    }
};

// Empty plantsDatabase array - plant data has been migrated to data/plants/*.json files
// This is kept as a fallback for backward compatibility
// Using var instead of const so it can be modified by plant-loader.js
var plantsDatabase = [];
