/**
 * Generate js/config.js from environment variables (local or CI).
 *
 * Usage:
 *   set SUPABASE_URL=... & set SUPABASE_ANON_KEY=... & node scripts/generate-config.js
 *   Or put the same keys in a root .env file (not committed).
 *
 * On Netlify production, /js/config.js is rewritten to the public-config function instead.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'js', 'config.js');

function loadDotEnv() {
    const envPath = path.join(ROOT, '.env');
    if (!fs.existsSync(envPath)) return;
    const text = fs.readFileSync(envPath, 'utf8');
    text.split(/\r?\n/).forEach(function (line) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.charAt(0) === '#') return;
        const eq = trimmed.indexOf('=');
        if (eq < 1) return;
        const key = trimmed.slice(0, eq).trim();
        let val = trimmed.slice(eq + 1).trim();
        if ((val.charAt(0) === '"' && val.charAt(val.length - 1) === '"') ||
            (val.charAt(0) === "'" && val.charAt(val.length - 1) === "'")) {
            val = val.slice(1, -1);
        }
        if (!process.env[key]) process.env[key] = val;
    });
}

function esc(value) {
    return JSON.stringify(value == null ? '' : String(value));
}

loadDotEnv();

const url = process.env.SUPABASE_URL || '';
const anon = process.env.SUPABASE_ANON_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || '';
const owner = process.env.SUPABASE_OWNER_EMAIL || process.env.STORE_OWNER_EMAIL || '';
const turnstile = process.env.TURNSTILE_SITE_KEY || '';

if (!url || !anon) {
    console.warn('[generate-config] SUPABASE_URL / SUPABASE_ANON_KEY missing — writing empty placeholders.');
}

const body = [
    '/**',
    ' * Generated by scripts/generate-config.js — do not commit real secrets.',
    ' * Local: copy .env.example → .env and run: npm run generate-config',
    ' * Netlify: /js/config.js is served by netlify/functions/public-config.js from env vars.',
    ' */',
    '(function () {',
    "    'use strict';",
    '    window.SUPABASE_URL = window.SUPABASE_URL || ' + esc(url) + ';',
    '    window.SUPABASE_ANON_KEY = window.SUPABASE_ANON_KEY || window.SUPABASE_PUBLISHABLE_KEY || ' + esc(anon) + ';',
    '    window.SUPABASE_OWNER_EMAIL = window.SUPABASE_OWNER_EMAIL || ' + esc(owner) + ';',
    '    window.TURNSTILE_SITE_KEY = window.TURNSTILE_SITE_KEY || ' + esc(turnstile) + ';',
    '})();',
    ''
].join('\n');

fs.writeFileSync(OUT, body, 'utf8');
console.log('[generate-config] Wrote', OUT);
